var GAME_LEVELS = [
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "    v                                     v                                     ",
   "                     v                                      v                   ",
   "                                                                                ",
   "                                v                  v                            ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                             o                                                  ",
   "                      a hh                                                      ",
   "                   xxxxxhhxxxxx                                             xx  ",
   "  xx         o   xxx!!!!!!!!!!x                            o                 x  ",
   "  x            xxx!!!!!!!!h!!!x                        hh                    x  ",
   "  x         xxxx!!h!!!!!!!!!!!x                   axxxxhhxxxxxx              x  ",
   "  x         x!!!!!!!!h!!!!!!!!x      o                                    o  x  ",
   "  x  @  xxxxx!!!!!!!!!!!!!!h!!x          hh            o             hh      x  ",
   "  xxxxxxx!!!!!!!!!!!!!!!!!!!!!x    xxxxxxhhxxxx=                     hhxxxxxxx  ",
   "  !!!!!!!!!!!!!h!!!!!!!!!!!!!!x   ox!!h!!!!!!!!!!!!!!!!!!h!!!!!                 ",
   "  !!!h!!!!!!!!!!!!!!!!!h!!!!!!x    x!!!!!!!!!!!!!!!!!!h!!!!!!!!                 ",
   "  !!!!!!!!!!!h!!!!!!!!!!!!!!!!x t xx!!!!!!!!h!!!!!!!!!!!!!!!!!!                 ",
   "  !!!!h!!!!!!!!!!!!!!!!!!!h!!!xxxxxx!!h!!!!!!!!!!!!!!!!!!!!!!!!                 ",
   "                                                             hh                 ",
   "                                                             !!                 "],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "        v                v            v                     v            v            v                 ",
   "                                                 v                                                      ",
   "   @                                                                                               v    ",
   "  xxx                           v                                                                       ",
   "    x                                                                       xxxxxx!!!!xxxxxx            ",
   "    x                                                                      xxxxxxx!!!!xxxxxxx           ",
   "    x                                                                     xx        o     a xx          ",
   "    x                                                                   axx        o o       xx         ",
   "    x  o                     v                v                          xx                  xx         ",
   "    x                                                                     xx                xx          ",
   "    xxxxxxx                                                                                             ",
   "          hhh                                                                                           ",
   "                                                                                  hh                    ",
   "                                                                                                        ",
   "                                                                                       hh               ",
   "                                                                                                        ",
   "                                                                                    hh                  ",
   "              o                                                                                         ",
   "  a                                                                                                     ",
   "            xxxxx         o           o          o                          axxxxxxxxxxxxxxxxxx         ",
   "             v v                                                          xxxxx               x         ",
   "                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                               o  a x         ",
   "!h!!!!!!!!x         x!!!!!xx!!!!!!!!!!!!!!!!h!!xx!!!!!!!!!                                    x         ",
   "!!!!h!!!!!x         x!!!!!xx!!!!!!!!!!!!!!!!!!!xx!!!!!!!!               xxxxxxxxxxxxxxxxxxxxxxx         ",
   "!!!!!!!!!!x         x!!!!!xx!!!!!!!!!h!!!!!!!!!xx!!!!!!!a              xx                               ",
   "!!!!!!h!!!x        hh!!!!!xx!!h!!!!!!!!!!!!!!!!xx!!!!!!                x                                ",
   "!!!!!!!!!!x o       x!!!!!xx!!!!!!!!!!!h!!!!!!!xx!!!!!     o          xx                                ",
   "!!!h!!!!!!x         x!!!!!!x!!!!!!!!!!!!!!!!!!!x!!!!  t                x                                ",
   "!!!!!h!!!!xxxxxxxxxxx!!!!!!!!!!h!!!!!!!!!!!!!!!!!!!xxxxxxxxxx!!!!!!!!!xx                                "],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     ",
   "   v  v               v                     v                    v                        v          x     ",
   "                                  v                 v                       v   v                    x     ",
   "                                                                                                     x     ",
   "            @                                                                                         xx   ",
   "          xxxxx                                                                                        xxx ",
   "     o    x   x                                                                                          xx",
   "     x        x=                !!!!h!!!!!!!!!!!!!!!!!!a                   o  o  o                        x",
   "              x                a!!!!!!!!!!!h!!!!!!!!!!!                      hhh                         =x",
   "              x  o              !!!!!h!!!!!!!!!!!!!!!!!a                  xxxhhhxxx                       x",
   "              x=                !!!!!!!!!!!!!!!!!!!h!!!                                   o               x",
   "              x                 !!!!!!!!!!!!!!h!!!!!!!!a                                                  x",
   "              x                a!!v!!!!h!!!!v!!!!!!!v!!                                  xxx              x",
   "              x                                                                                           x",
   "              x                                                                    o                     ax",
   "              x                                                                                           x",
   "              x                                                                   hha                 o xx ",
   "              x  o              xxxxxxxxxxx              hh                                            xxx ",
   "              x                xx      xxxxx           xxhhxx                                       o xx   ",
   "              x                x       xxxxxx         xxxxxxxx        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    ",
   "              x               xx       xxxxxxxxxxxxxxxxxxxxxxx=       x                                    ",
   "              x               x        x                        o    xx                                    ",
   "              x       hh     xx        x  t                     o   =x                                     ",
   "              xxxxxxxxhhxxxxxxx        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                     "],
  ["    x     x  xxx   x   x                                 ",
   "     x   x  x   x  x   x                                       ",
   "      xxx   x   x  x   x                                      ",
   "       x    x   x  x   x                           ",
   "       x     xxx    xxx                                       ",
   "                                                                        ",
   "    x     x   xxx  xx    x |                                                                ",
   "    x     x    x   x x   x |                                                               ",
   "    x  x  x    x   x   x x |                                          ",
   "    x  x  x    x   x    xx |                                    ",
   "     xx xx    xxx  x     x x                                          ",
   "                                           ",
   "                                                    "]
 ];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
